// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/token-srv/proto/record/record.proto

/*
Package record is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/token-srv/proto/record/record.proto

It has these top-level messages:
	Token
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	SearchRequest
	SearchResponse
	GenerateRequest
	GenerateResponse
*/
package record

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Token struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Created   int64  `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	Updated   int64  `protobuf:"varint,5,opt,name=updated" json:"updated,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Token) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Token) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Token) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Token) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Token) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CreateRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type UpdateRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SearchRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Limit     int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset    int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SearchRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Tokens []*Token `protobuf:"bytes,1,rep,name=tokens" json:"tokens,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchResponse) GetTokens() []*Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type GenerateRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *GenerateRequest) Reset()                    { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()               {}
func (*GenerateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GenerateRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type GenerateResponse struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GenerateResponse) Reset()                    { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()               {}
func (*GenerateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GenerateResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*GenerateRequest)(nil), "GenerateRequest")
	proto.RegisterType((*GenerateResponse)(nil), "GenerateResponse")
}

func init() {
	proto.RegisterFile("github.com/microhq/token-srv/proto/record/record.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xed, 0x6e, 0xd3, 0x50,
	0x0c, 0x6d, 0xd2, 0x36, 0x30, 0x6f, 0x49, 0x8a, 0x85, 0x50, 0x14, 0x0d, 0xa8, 0xae, 0x84, 0x34,
	0x09, 0x7a, 0x33, 0x86, 0xc4, 0x0b, 0x80, 0xc4, 0xff, 0x00, 0x0f, 0x90, 0x25, 0x1e, 0x8d, 0x58,
	0x73, 0xb3, 0x9b, 0x94, 0x7f, 0xbc, 0x06, 0xcf, 0x8b, 0xe2, 0x7b, 0xa3, 0x7c, 0x48, 0x83, 0xfe,
	0x6a, 0x6d, 0x1f, 0xfb, 0x1e, 0xfb, 0x9c, 0xc0, 0xc7, 0x1f, 0x65, 0xbb, 0x3f, 0xde, 0xca, 0x5c,
	0x1d, 0x92, 0x43, 0x99, 0x6b, 0xb5, 0x7f, 0x48, 0x5a, 0xf5, 0x93, 0xaa, 0x5d, 0xa3, 0x7f, 0x25,
	0xb5, 0x56, 0xad, 0x4a, 0x34, 0xe5, 0x4a, 0x17, 0xf6, 0x47, 0x72, 0x4e, 0xfc, 0x86, 0xf5, 0xb7,
	0x0e, 0x86, 0x01, 0xb8, 0x65, 0x11, 0x39, 0x5b, 0xe7, 0xea, 0x2c, 0x75, 0xcb, 0x02, 0x2f, 0xe1,
	0xac, 0xca, 0x0e, 0xd4, 0xd4, 0x59, 0x4e, 0x91, 0xcb, 0xe9, 0x21, 0x81, 0x08, 0xab, 0x2e, 0x88,
	0x96, 0x5c, 0xe0, 0xff, 0x18, 0xc1, 0x93, 0x5c, 0x53, 0xd6, 0x52, 0x11, 0xad, 0xb6, 0xce, 0xd5,
	0x32, 0xed, 0xc3, 0xae, 0x72, 0xac, 0x0b, 0xae, 0xac, 0x4d, 0xc5, 0x86, 0x62, 0x07, 0xfe, 0x27,
	0x06, 0xa5, 0xf4, 0x70, 0xa4, 0xa6, 0xc5, 0x4b, 0x58, 0x33, 0x6d, 0x66, 0x72, 0x7e, 0xe3, 0x49,
	0x66, 0x97, 0x9a, 0xa4, 0xd8, 0x40, 0xd0, 0xc3, 0x9b, 0x5a, 0x55, 0x0d, 0x89, 0xd7, 0xe0, 0x7f,
	0xa6, 0x7b, 0x1a, 0x06, 0xcc, 0xf6, 0xe8, 0x5a, 0x7a, 0x80, 0x6d, 0x79, 0x09, 0xe7, 0x29, 0x65,
	0xc5, 0x63, 0x0d, 0xef, 0xe0, 0xc2, 0x94, 0x0d, 0xfc, 0x3f, 0x8c, 0x76, 0xe0, 0x7f, 0xe7, 0x5d,
	0x4e, 0x5e, 0xa0, 0x87, 0x5b, 0x36, 0x0a, 0xfc, 0xaf, 0x94, 0xe9, 0x7c, 0x3f, 0x0c, 0x18, 0x1d,
	0xde, 0x79, 0xec, 0xf0, 0xee, 0xe8, 0xf0, 0xcf, 0x61, 0x7d, 0x5f, 0x1e, 0xca, 0x96, 0xd5, 0x58,
	0xa6, 0x26, 0xc0, 0x17, 0xe0, 0xa9, 0xbb, 0xbb, 0x86, 0x5a, 0xab, 0x86, 0x8d, 0xc4, 0x35, 0x04,
	0xfd, 0x83, 0x76, 0xc3, 0x57, 0xe0, 0x31, 0xbb, 0x26, 0x72, 0xb6, 0xcb, 0x11, 0x67, 0x9b, 0x15,
	0x09, 0x84, 0x5f, 0xa8, 0x22, 0x3d, 0xd9, 0xf2, 0x1f, 0x24, 0xc5, 0x35, 0x6c, 0x86, 0x86, 0x53,
	0xce, 0x78, 0xf3, 0xc7, 0x05, 0x2f, 0x65, 0x5f, 0xe2, 0x7b, 0x78, 0xda, 0x37, 0xe3, 0x46, 0xce,
	0x1e, 0x8e, 0x9f, 0xc9, 0xf9, 0x64, 0xb1, 0xc0, 0xb7, 0xe0, 0x19, 0x5b, 0x60, 0x20, 0x27, 0x76,
	0x8a, 0x43, 0x39, 0xf3, 0xcb, 0x02, 0xdf, 0xc0, 0xaa, 0xd3, 0x17, 0x2f, 0xe4, 0xc8, 0x05, 0xb1,
	0x2f, 0xc7, 0xa2, 0x9b, 0x99, 0xc6, 0x37, 0x18, 0xc8, 0x89, 0xc3, 0xe2, 0x50, 0xce, 0x0c, 0xc5,
	0x60, 0x23, 0x2b, 0x06, 0x72, 0x62, 0x87, 0x38, 0x94, 0x33, 0xbd, 0x19, 0x6c, 0x04, 0xc0, 0x40,
	0x4e, 0xa4, 0x8f, 0x43, 0x39, 0x55, 0x46, 0x2c, 0x6e, 0x3d, 0xfe, 0x4c, 0x3f, 0xfc, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x46, 0x17, 0x64, 0xb7, 0xe0, 0x03, 0x00, 0x00,
}
